### ISSUE TITLE
Did you try nesting Schemas? You can only nest using refs or arrays.

### ISSUE THREAD

**Issue by molerat619** [cbargren/express-brute-mongoose#13]
When I follow the readme, I get this error using the default schema:

```
/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:362
    throw new TypeError('Undefined type at `' + path +
    ^

TypeError: Undefined type at `paths._id`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Function.Schema.interpretAsType (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:362:11)
    at Schema.path (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:305:29)
    at Schema.add (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:217:12)
    at Schema.add (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:212:14)
    at new Schema (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/schema.js:73:10)
    at Mongoose.model (/Applications/XAMPP/xamppfiles/htdocs/everest/node_modules/mongoose/lib/index.js:294:14)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/everest/server/auth/local/index.js:15:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/everest/server/auth/index.js:13:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by molerat619** [comment]
After copying the default schema to the route file like so, it works like a charm:

```
var model = mongoose.model('bruteforce', new mongoose.Schema({
  _id: { type: String },
  data: {
    count: Number,
    lastRequest: Date,
    firstRequest: Date
  },
  expires: { type: Date, index: { expires: '1d' } }
}, { collection: 'bruteforce' }));
```

**Comment by cbargren** [comment]
That's weird, I haven't seen that before. What versions of mongodb and mongoose were you on?
